# Nixpacks configuration for optimized builds
[phases.setup]
providers = ['node']

[phases.install]
cmd = 'npm ci --omit=dev --prefer-offline --no-audit --no-fund'

[phases.build]
cmd = '''
  (cp curriculum_precise.db ./ || cp prisma/curriculum.db ./) && 
  npx prisma generate && 
  npm run build
'''

[phases.start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
NPM_CONFIG_UPDATE_NOTIFIER = 'false'
NPM_CONFIG_FUND = 'false'
NPM_CONFIG_AUDIT = 'false'
