# Nixpacks configuration for optimized builds
[phases.setup]
providers = ['node']

[phases.install]
# Need dev dependencies for build - can't omit them
cmd = 'npm ci --prefer-offline --no-audit --no-fund --progress=false'

[phases.build]
cmd = '''
  (cp curriculum_precise.db ./ || cp prisma/curriculum.db ./) && 
  npx prisma generate && 
  npm run build
'''

[phases.start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
NPM_CONFIG_UPDATE_NOTIFIER = 'false'
NPM_CONFIG_FUND = 'false'
NPM_CONFIG_AUDIT = 'false'
NPM_CONFIG_PROGRESS = 'false'
