# Railway Deployment Configuration - Optimized for Speed
[build]
  builder = "DOCKERFILE"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[variables]
  NODE_ENV = "production"
  DATABASE_URL = "file:./curriculum.db"
  YOUTUBE_API_KEY = "${{YOUTUBE_API_KEY}}"
  # Skip checks to speed up build
  SKIP_ENV_VALIDATION = "true"
  NEXT_TELEMETRY_DISABLED = "1"
