# Railway Deployment Configuration
# This file tells Railway how to deploy your app

[build]
  builder = "NIXPACKS"
  buildCommand = "npm install && npx prisma generate && npm run build"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[variables]
  NODE_ENV = "production"
  YOUTUBE_API_KEY = "${{YOUTUBE_API_KEY}}"
