# Railway Deployment Configuration
# This file tells Railway how to deploy your app

[build]
  builder = "NIXPACKS"
  # Optimize build command for faster deployment
  buildCommand = "npm ci --only=production && (cp curriculum_precise.db ./ || cp prisma/curriculum.db ./) && npx prisma generate && npm run build"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10
  
  # Increase memory and CPU for faster builds
  memoryGB = 2
  cpuCount = 2

[variables]
  NODE_ENV = "production"
  DATABASE_URL = "file:./curriculum.db"
  YOUTUBE_API_KEY = "${{YOUTUBE_API_KEY}}"
  # Skip type checking and linting during build
  SKIP_ENV_VALIDATION = "true"
